### ISSUE TITLE
BYPASS_MONGO_VALIDATION=true is not bypassing the MongoDB version check

### ISSUE THREAD

**Issue by k-ahn** [RocketChat/rocketchat-server-snap#48] opened 2022-07-24 09:18 UTC
**Description**:

Environment variable BYPASS_MONGO_VALIDATION=true is not bypassing the MongoDB version check

**Steps to reproduce**:

1. Install via snap **sudo snap install rocketchat-server** or switch branches to "4.x/stable"
2. Get system message: "MongoDB version 3.6.23 is deprecated, please upgrade your installation."
3. Add **export BYPASS_MONGO_VALIDATION=true** to /etc/profile 

**Expected behavior:**

MongoDB version check should be bypassed and Admins DO NOT receive a Rocket.Cat alert

**Actual behavior**:

MongoDB version check runs and Admins DO receive a Rocket.Cat alert

**Server Setup Information**:

- Version of Rocket.Chat Server: 4.1.2
- Operating System: Ubuntu 18.04.5 LTS on Raspberry Pi 4
- Deployment Method: snap
- Number of Running Instances: 1
- NodeJS Version: v12.22.7
- MongoDB Version: 3.6.23 / wiredTiger (oplog Enabled)

**Additional context**:

I have exactly [this issue](https://github.com/RocketChat/rocketchat-server-snap/issues/29) where i've upgraded Rocket Chat to 4.1.2 via a Snap and i'm getting the message "**MongoDB version 3.6.23 is deprecated, please upgrade your installation.**". 

The thread goes on to state **"The mongo update will happen shortly. You can ignore the deprecation message in the meantime."**, but that was 9 months ago. 

I've no issue waiting, however, every Admin is getting frequently spammed with Rocket.Cat alerts in the meantime for which there is no corrective action available to us.

[This post](https://docs.rocket.chat/getting-support#mongodb-versions) states:

_It's possible to bypass the MongoDB version check by using the environment variable BYPASS_MONGO_VALIDATION=true. Bare in mind that this work around should be used only when extrictly necessary and may prevent some functionalities to work properly or even prevent the server to start._

This would seem the best course of action but it doesn't work. I've added the variable to /etc/profile and confirmed it is available before Rocket Chat server starts.

Help

**Comment by debdutdeb** [comment] 2022-08-27 20:19
You can't set environment variables for snaps like that. Read [here](https://docs.rocket.chat/quick-start/deploying-rocket.chat/rapid-deployment-methods/snaps/snap-faq#how-do-i-change-other-environmental-variables-in-my-snap). Closing since not a bug. Please feel free to continue asking any other question you might have :)

**Closed as completed by debdutdeb** 2022-08-27 20:19 UTC

**Comment by k-ahn** [comment] 2022-12-03 17:47
Thanks @debdutdeb but i still can't get this to work. 

Here's the output from my terminal:

```
user@server: /var/snap/rocketchat-server/common$ cat bypass_mongo_validation.env 
BYPASS_MONGO_VALIDATION=true
```

Where i then restart the services and/or restart the server, i still get the "MongoDB version 3.6.23 is deprecated, please upgrade your installation." Rocket.Cat notification

**Comment by debdutdeb** [comment] 2022-12-03 17:56
Which version are you in? In the latest it works that I can gurantee. You should update, considering it's complaining about mongo 3.6, you must be on some old track.

**Comment by debdutdeb** [comment] 2022-12-03 17:57
Secondly, the environment variable is in case mongodb version is unsupported. It does not handle rocket.cat notifications.

**Comment by k-ahn** [comment] 2022-12-04 10:30
Here's the package info:

```
channels:
  latest/stable:    3.18.2 2021-12-06 (1495) 217MB -
  latest/candidate: 3.18.2 2021-12-06 (1495) 217MB -
  latest/beta:      3.18.2 2021-12-06 (1495) 217MB -
  latest/edge:      3.18.2 2021-12-06 (1495) 217MB -
  4.x/stable:       4.1.2  2021-12-15 (1496) 212MB -
  4.x/candidate:    4.1.2  2021-12-15 (1496) 212MB -
  4.x/beta:         4.6.4  2022-06-07 (1519) 282MB -
  4.x/edge:         4.1.2  2021-11-19 (1496) 212MB -
  3.x/stable:       3.18.2 2021-11-28 (1495) 217MB -
  3.x/candidate:    3.18.2 2021-11-28 (1495) 217MB -
  3.x/beta:         3.18.2 2021-11-28 (1495) 217MB -
  3.x/edge:         3.18.2 2021-11-28 (1495) 217MB -
  2.x/stable:       2.4.9  2020-02-19 (1423) 272MB -
  2.x/candidate:    ↑
  2.x/beta:         ↑
  2.x/edge:         ↑
installed:          4.1.2             (1496) 212MB -
```

The challenge i have is that i'm running the latest stable version, which is the version triggering the deprecated message. 

There's no issue with the installation so i'm happy to wait for the next release, however, we get spammed daily by the Rocket.Cat alert and hence want to prevent the check.

**Comment by debdutdeb** [comment] 2022-12-04 14:49
What is your snapd version? And host information? Please share.

**Comment by k-ahn** [comment] 2022-12-04 15:32
```
Version of Rocket.Chat Server: 4.1.2
Operating System: Ubuntu 18.04.5 LTS on Raspberry Pi 4
Deployment Method: snap
Number of Running Instances: 1
NodeJS Version: v12.22.7
MongoDB Version: 3.6.23 / wiredTiger (oplog Enabled)
```

```
snap    2.57.6
snapd   2.57.6
series  16
ubuntu  18.04
kernel  5.3.0-1042-raspi2
```
